In [1]:
import numpy as np


In [2]:
array = np.array([-1,4,-9,4,3,7])
array

array([-1,  4, -9,  4,  3,  7])

In [3]:
len(array)

6

In [4]:
array[1]

4

In [5]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2,7,5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [6]:
my_3d_array.ndim

3

In [7]:
matrix1 = np.arange(6).reshape(2,3)
matrix2 = np.arange(6).reshape(3,2)
np.dot(matrix1,matrix2)

array([[10, 13],
       [28, 40]])

In [8]:
###Linear Algebra

In [10]:
matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
#Transpose of matrix
matrix.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])