In [1]:
import numpy as np


In [2]:
np.__version__

'1.15.3'

In [3]:
#Creating np_array from list
list = [1,2,3,4,5,6]
np_array = np.array(list)
np_array

array([1, 2, 3, 4, 5, 6])

In [4]:
np_array * 10


array([10, 20, 30, 40, 50, 60])

In [5]:
np_array

array([1, 2, 3, 4, 5, 6])

In [8]:
array = np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
np.arange(10,34)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [10]:
np.arange(10,34).size

24

In [11]:
np.arange(10,34,4)

array([10, 14, 18, 22, 26, 30])

In [12]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [13]:
np.linspace(3,5,8)

array([3.        , 3.28571429, 3.57142857, 3.85714286, 4.14285714,
       4.42857143, 4.71428571, 5.        ])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])